--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6
-- Dumped by pg_dump version 16.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: jobb_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobb_post (
    post_id integer NOT NULL,
    post_desc character varying(255),
    post_profile character varying(255),
    post_tech_stack character varying(255)[],
    req_experience integer
);


ALTER TABLE public.jobb_post OWNER TO postgres;

--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id integer NOT NULL,
    brand character varying(255),
    description character varying(255),
    image_data oid,
    image_name character varying(255),
    image_type character varying(255),
    name character varying(255),
    price numeric(38,2),
    product_available boolean NOT NULL,
    release_date timestamp(6) without time zone,
    stock_quantity integer NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users1; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users1 (
    id integer NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users1 OWNER TO postgres;

--
-- Name: users1_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users2; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users2 (
    id integer NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users2 OWNER TO postgres;

--
-- Name: users2_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: jobb_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jobb_post (post_id, post_desc, post_profile, post_tech_stack, req_experience) FROM stdin;
1	Backend Java Spring Boot Developer	Java Developer	{Java,"Spring Boot",MySQL}	3
2	React and Angular focused UI work	Frontend Developer	{React,Angular,TypeScript}	2
3	CI/CD pipelines and cloud infrastructure	DevOps Engineer	{Docker,Kubernetes,AWS,Jenkins}	4
4	Java + React full stack role	Full Stack Engineer	{Java,React,Spring,PostgreSQL}	5
5	ETL pipelines and big data tools	Data Engineer	{Python,Spark,Hadoop,Airflow}	3
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, brand, description, image_data, image_name, image_type, name, price, product_available, release_date, stock_quantity) FROM stdin;
1	TechCorp	High-end smartphone with 5G support	\N	x1.jpg	image/jpeg	Smartphone X1	799.99	t	2024-10-01 00:00:00	50
2	ComputeTech	15-inch professional laptop with 32GB RAM	\N	laptop15.png	image/png	Laptop Pro 15	1299.50	t	2023-09-15 00:00:00	20
3	SoundBlast	Noise-canceling wireless earbuds	\N	earbuds.jpg	image/jpeg	Wireless Earbuds	149.95	t	2024-02-10 00:00:00	100
4	HealthPlus	Fitness smartwatch with heart rate monitor	\N	smartwatch.png	image/png	Smartwatch Fit	199.99	t	2024-06-01 00:00:00	75
\.


--
-- Data for Name: users1; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users1 (id, password, username) FROM stdin;
13	$2a$12$E63sX8zbACRKL9YAPhOURufH22Cpu3aYgj2imFsOgexI4ldCQGA2W	Birbal
\.


--
-- Data for Name: users2; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users2 (id, password, username) FROM stdin;
1	$2a$12$dDURvq4jymmGNjhReTMpLeZkVtxhnfPLK1U92hIXExg0eR4n1xQpy	Birbal
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 5, true);


--
-- Name: users1_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users1_id_seq', 13, true);


--
-- Name: users2_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users2_id_seq', 1, true);


--
-- Name: jobb_post jobb_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobb_post
    ADD CONSTRAINT jobb_post_pkey PRIMARY KEY (post_id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: users2 users2_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users2
    ADD CONSTRAINT users2_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

